name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Install Spigot Build tools (1.8.8)
      uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: 1.8.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate release tag and get commit message
      id: tag
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
        COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "::set-output name=release_tag::${COMMIT_HASH}"
        echo "::set-output name=commit_message::${COMMIT_MESSAGE}"

    - name: Exclude JAR with "original" in the name
      run: |
        mkdir -p filtered-target
        find target/ -type f -name "*.jar" ! -name "*original*.jar" -exec cp {} filtered-target/ \;

    - name: Add filtered Jar to GitHub releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.REPO_TOKEN }}"
        automatic_release_tag: "${{ steps.tag.outputs.release_tag }}"
        prerelease: false
        title: "Release [${{ steps.tag.outputs.release_tag }}]: ${{ steps.tag.outputs.commit_message }}"
        files: |
          filtered-target/*.jar




